### ISSUE TITLE
Error reading SSH protocol banner

### ISSUE THREAD

**Issue by bryanmcaninch** [Peco602/findwall#3]
`user@unknown findwall % python findwall.py --ssh-key ~/.ssh/key.pem --ssh-host www.example.com --ssh-port 443 --ssh-username user --ports 1-65535`

_Exception (client): Error reading SSH protocol banner
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2271, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2094, in run
    self._check_banner()
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2275, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

[!] Error reading SSH protocol banner_

…

_Scanning...:  16%|██████████████████████████████████                                                                                                                                                                                 | 10594/65535 [2:57:46<15:21:51,  1.01s/it]Exception (client): Error reading SSH protocol banner
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2271, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2094, in run
    self._check_banner()
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2275, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

[!] Error reading SSH protocol banner

Scanning...:  18%|██████████████████████████████████████▌_

The above errors repeat as the scan continues. As depicted, my scan is currently 18% complete at the time of this submission.

**Comment by Peco602** [comment]
Are you sure you can access www.example.com via ssh? Are you the owner of the VPS pointed by www.example.com?

**Comment by bryanmcaninch** [comment]
Yes, it's a Kali Linux EC2 instance to which I have SSH and root access.

I successfully ran a scan with ports 1-1024 just prior to this one with which I specified ports 1-65535.

**Comment by Peco602** [comment]
I think the problem is due to the high number of connections to the SSH server.

I have just pushed an update on the `dev` branch where I have implemented:
1. SSH TCP, banner and auth timeouts
2. Possibility to get the password interactively and not only via command-line

**Comment by bryanmcaninch** [comment]
Thank you. As an extra measure of due diligence, I re-executed with the original arguments (ports 1-1024) error-free.
